config/routes.rb
Rails.application.routes.draw do

  root 'notes#index'

  # root 'pages#home'


  devise_for :users, controllers: {
    registrations:  'users/registrations',
    sessions:  'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'notes/archived', :to => 'notes#archived'
  get 'notes/bin', :to => 'notes#bin'
  get 'notes/show_label', :to => 'notes#show_label'
  get 'notes/edit_color', :to => 'notes#edit_color'
  get "note/notesshow" => 'note#notesshow', :as => :notesshow
  get 'notes/search', :to => 'notes#search'
  get '/update/:id' , to: "root#update"
  get 'notes/label_note', :to => 'notes#label_note'
  # get 'notes/home', :to => 'notes#home'
  # get 'notes/user', :to => 'notes#user'

  resources :notes do
    member do
      put :archive
      put :active
      put :notarchive
      put :deleted_at
      patch :soft_delete
      put :restore
      put :pinned
      put :unpinned
      patch :add_label
      get :update_color
      post :create_copy
      post :copy
      post :copy_note
      delete :delete_image
      delete :delete_background_image
      patch :set_reminder
      post :send_mail
    end
  end
  resources :labels

  # Rails.application.routes.draw do
  get 'pages/home'
  # resources :consumers
  # # mount_devise_token_auth_for 'User', at: 'auth'

  #   root to: 'users#new'

  #   get 'users/new' => 'users#new', as: :new_user
  #   post 'users' => 'users#create'

  #   # ----- add these lines here: -----

  #   # log in page with form:
  #   get '/login'     => 'sessions#new'

  #   # create (post) action for when log in form is submitted:
  #   post '/login'    => 'sessions#create'

  #   # delete action to log out:
  #   delete '/logout' => 'sessions#destroy'

  #     # ----- end of added lines -----

  # end

end

app/models/note.rb
class Note < ApplicationRecord

  validates :title, presence: true
  validates :content, presence: true
  validates :title, length: { in: 6..20 }
  validates :content, length: { in: 6..20 }

  acts_as_paranoid
  has_and_belongs_to_many :labels
  has_one_attached :image


    default_scope { where(deleted_at: nil) }
    scope :with_deleted, -> { where.not(deleted_at: nil) }

    def soft_delete
      self.deleted_at = DateTime.now
      save
    end

  # validates :reminder, presence: true, future_date: true

  # validate :reminder_cannot_be_in_the_past
  # def reminder_cannot_be_in_the_past
  #   errors.add(:reminder_date, "can't be in the past") if reminder.present? && reminder < Date.today
  # end

  COLOR_TYPE = { "White" => 'White',"Red" => '#7c0a02', "Green" => '#004225', "Pista-Green"  => '#d6c675' , "AntiqueWhite"  => '#faebd7' , "Blue Bell"  => '#a2a2d0' }.freeze

  scope :active, -> { where(status:"active") }
  scope :archived, -> { where(status:"archived") }
  scope :notdel, -> { where(stage:"notdel") }
  scope :del, -> { where(stage:"del") }
  scope :pinned, -> { where(pin: true) }
  scope :unpinned, -> { where(pin: false) }

  def formatted_date
    updated_at.strftime('%d-%b-%y')
  end
  def formatted_time
    updated_at.localtime.strftime("%H:%M:%S")
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!

  skip_before_action :verify_authenticity_token
  def index
    @new_note = Note.new
    @soft_deleted_notes = Note.only_deleted
    @labels = Label.all
    if params[:query].present?
      @notes = Note.where("title ILIKE ? OR content LIKE ? ","%#{params[:query]}%", "%#{params[:query]}%" )
      # @pagy, @notes = pagy((Note.search_notes(params[:query])))
    else
      # @notes = Note.all
      @pagy, @notes = pagy((Note.all), items: 20)
      @notes = Note.order('created_at DESC')
    end
    #  render json: { status: 'ok' }, status: 200
  end


  def show
    @labels = Label.all
    @note = Note.find(params[:id])
      respond_to do |format|
      format.js
    end
  end

  def new
    @notes = Note.all
    @labels = Label.all
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path }
        format.js   # This will render create.js.erb
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render :index }
      end
    end
  end

  def edit
    @note = Note.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      respond_to do |format|
        # format.html {redirect_to notes_path}
        format.js
      end
    else
      redirect_to notes_path, alert: 'Failed to update note.'
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to notes_bin_path :id
  end

  def archive
    @note = Note.find(params[:id])
    @note.update(status: 'archived')
    @note.update(pin: 'false')
    redirect_to :notes, notice: 'Successfully Archived'
  end

  def notarchive
    @note = Note.find(params[:id])
    @note.update(status: 'active')
    # render plain: "OK"

    redirect_to :notes, notice: 'Successfully restored'
  end

  def soft_delete
    @note = Note.find(params[:id])
    @note.update(stage: 'del')
    # @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
      format.js   # This will look for a destroy.js.erb file
    end
  end


  def restore
    @note = Note.find(params[:id])
    @note.update(stage: 'notdel')
    @note.update(deleted_at: nil)
    redirect_to :notes_bin, notice: 'Successfully restored'
  end

  def pinned
    @note = Note.find(params[:id])
    @note.update(pin: 'true')
    @note.update(updated_at:Time.now)
    redirect_to :notes
  end

  def unpinned
    @note = Note.find(params[:id])
    @note.update(pin: 'false')
    redirect_to :notes
  end

  def archived
    @notes = Note.all
    @labels = Label.all
    if params[:query].present?
      @notes = Note.where("(title.upcase LIKE ? OR lower(content) LIKE ? ","%#{params[:query]}%", "%#{params[:query]}%")
    else
      @notes = Note.all
    end
  end

  def bin
    @notes = Note.all
    @labels = Label.all
    if params[:query].present?
      @notes = Note.where("title LIKE ? OR content LIKE ? ","%#{params[:query]}%", "%#{params[:query]}%" )
    else
      @notes = Note.all
    end
  end

  def show_label
    @notes = Note.all
    @labels = Label.all
  end

  def label_note
    @notes = Note.all
    @labels = Label.all
  end

  def active
    @notes = Note.all
  end

  def add_label
    @note = Note.find(params[:id])
    @labels = Label.where(id: params[:note][:label_ids])
    @note.labels = @labels

    if @note.save
      flash[:notice] = 'Label added successfully!'
      redirect_to notes_path
    else
      flash[:alert] = 'Error adding label'
      render :edit
    end
  end

  def copy
    @note = Note.find(params[:id])
    @new_note = @note.dup
    @new_note.pin = false
    if @new_note.save
      redirect_to notes_path, notice: 'Note was successfully copied.'
    else
      redirect_to labels_path, alert: 'Failed to copy note.'
    end
  end

  def set_reminder
    @note = Note.find(params[:id])
    if @note.update(note_params)
      flash[:notice] = 'Reminder set successfully!'
      redirect_to @note
    else
      render 'edit'
    end
  end

  def delete_image
    @note = Note.find(params[:id])

    begin
      @note.image.purge
      flash[:success] = "Image deleted successfully."
    rescue => e
      flash[:error] = "Failed to delete the image: #{e.message}"
    end
    redirect_to :notes
  end

  def home

  end

  def send_mail
    @note = Note.find(params[:id])
    NotemailerMailer.send_mail_note(@note).deliver.now
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content ,:label_id,:color,:state , :status ,:pin , :image ,:background_image,:deleted_at , :unique_id , :reminder)
    end
end

app/helpers/notes_helper.rb
module NotesHelper

end

app/views/notes/_edit.html.erb
<div id="editModal" class="modal fade" role="model-dialog" id= "card-<%= note.id %>">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <%= form_for(note) do |form| %>
        <div style="background-color: <%= @note.color.downcase %>;", class='T'>
          <div class='row'>
            <div class='col'  >
              <%= form.text_area :title, placeholder: 'Title' %>
            </div>
            <% note.errors.full_messages_for(:title).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>

          <div class='row' class='mt-10 col-md-12'>
            <div class='col' class='input'>
              <%= form.text_area :content, placeholder: 'Content' %>
            </div>
            <% note.errors.full_messages_for(:content).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
          <div class="row">
            <div class="col">
              <ul>
                <% note.labels.each do |label| %>
                  <%= label.label_name %>
                  <h7>/</h7>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="row">
            <div class="col col-sm-3">
              <%= form_for @note do |f| %>
                Color: <%= f.select :color , options_for_select(Note::COLOR_TYPE,selected:@note.color)  %>
                <%#= f.submit 'Update' %>
              <% end %>
            </div>
            <div class="col col-sm-2">
              <div class="dropdown">
                <button class="btn btn-success dropdown-toggle"
                        type="button"
                        id="label_name"
                        data-bs-toggle="dropdown"
                        aria-expanded="true">
                    Add Label
                </button>
                <ul class="dropdown-menu"
                  aria-labelledby="multiSelectDropdown">
                  <%= form_for @note, url: {action: "add_label"} do |form| %>
                    <li>
                      <%= form.collection_check_boxes(:label_ids, Label.all, :id, :label_name, { multiple: true }) %>
                      <%= form.submit "Add label" %>
                      <% end %>
                    </li>
                </ul>
              </div>
            </div>
            <div class="col col-sm-4">
              <% if @note.image.attached? %>
                <%= image_tag (@note.image), height: 100 , width: 200 %>
                  <%= link_to "Delete Image", delete_image_note_path(@note), method: :delete, data: { confirm: "Are you sure you want to delete this image?" } %>
                <% else %>
                  <%= form.file_field :image %>
              <% end %>
            </div>

            <div class="col col-sm-2">
              <li class="nav-item dropdown px-2" >
                <a class="nav-link dropdown-toggle" href="#" role="button"    data-bs-toggle="dropdown" aria-expanded="false">
                    <strong>more..</strong>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <button class="btn btn-success dropdown-toggle"
                          type="button"
                          id="label_name"
                          data-bs-toggle="dropdown"
                          aria-expanded="true">
                        Add Label
                    </button>
                    <ul class="dropdown"
                      aria-labelledby="multiSelectDropdown">
                      <%= form_for @note, url: {action: "add_label"} do |form| %>
                        <li>
                          <%= form.collection_check_boxes(:label_ids, Label.all, :id, :label_name, { multiple: true }) %>
                          <%= form.submit "Add label" %>
                          <% end %>
                        </li>
                    </ul>
                  </li>
                  <li>
                    <%= link_to 'Create Copy', copy_note_path(note), method: :post%>
                  </li>
                  <li>
                    <%= link_to 'Delete Note', [:soft_delete, note], method: :put %>
                  </li>
                </ul>
              </li>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-9">
              <%= form.submit 'save' %>
            </div>
            <div class='col-sm-3'>
              <% if note.created_at.strftime('%d-%b-%y') != note.updated_at.strftime('%d-%b-%y') %>
                Edited <%= note.formatted_date %>
              <% end %>
              <br>
              <% if note.created_at.strftime('%H:%M') != note.updated_at. strftime('%H:%M') %>
                Edited <%= note.formatted_time %>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-9">
              <%= link_to 'Edit', edit_note_path(note) %></td>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/_edit_modal.erb
<div class='modal fade editModal' role="model-dialog" id='card-<%= note.id %>' tabindex="-1">
  <div class='modal-dialog modal-lg'>
    <div class='modal-content'>
      <%= form_for(note,remote: true ) do |form| %>
        <div style="background-color: <%= @note.color.downcase %>;", class='T'>
          <div class='row'>
            <div class='col'>
              <%= form.text_area :title, placeholder: 'Title' %>
            </div>
            <% note.errors.full_messages_for(:title).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
          <div class='row mt-10 col-md-12'>
            <div class='col input'>
              <%= form.text_area :content, placeholder: 'Content' %>
            </div>
            <% note.errors.full_messages_for(:content).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
          <div class='row'>
            <div class='col'>
              <ul>
                <% note.labels.each do |label| %>
                  <%= label.label_name %>
                  <h7>/</h7>
                <% end %>
              </ul>
            </div>
          </div>

          <div class='row'>
            <div class='col'>
              <%= form.label :reminder, "Set Reminder Date" %>
              <%= form.datetime_field :reminder %>
            </div>
          </div>
          <%= form_for @note, url: {action: "add_label"} do |f| %>
          <% end %>

          <div class='row'>
            <div class='col col-sm-3'>
              Color: <%= form.select :color , options_for_select(Note::COLOR_TYPE,selected:@note.color)  %>
            </div>
            <div class='col col-sm-2'>
            </div>
            <div class='col col-sm-4'>
              <% if @note.image.attached? %>
                <%= image_tag (@note.image), height: 100 , width: 200 %>
                  <%= link_to "Delete Image", delete_image_note_path(@note), method: :delete, data: { confirm: "Are you sure you want to delete this image?" } %>
                <% else %>
                  <%= form.file_field :image %>
              <% end %>
            </div>
            <div class='col col-sm-2'>
              <li class='nav-item dropdown px-2'>
                <a class='nav-link dropdown-toggle' href="#" role="button"    data-bs-toggle="dropdown" aria-expanded="false">
                    <strong>more..</strong>
                </a>
                <ul class='dropdown-menu'>
                  <li>
                    <ul class="dropdown"
                      aria-labelledby="multiSelectDropdown">
                      <%= form_for @note, url: {action: "add_label"} do |f| %>
                        <li>
                          <%= f.collection_check_boxes(:label_ids, Label.all, :id, :label_name, { multiple: true }) %>
                          <%= f.submit "Add label" %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                  <% if note.stage == 'notdel'%>
                    <li>
                      <%= link_to 'Create Copy', copy_note_path(note), method: :post%>
                    </li>
                    <li>
                      <%= link_to 'Delete Note', [:soft_delete, note], method: :patch , remote: true %>
                    </li>
                    <% if note.status == "active" %>
                      <li>
                        <%= link_to 'Archived', [:archive, note], method: :put %>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to 'UnArchived', [:notarchive, note], method: :put %>
                      <li>
                    <% end %>
                    <% if note.pin %>
                      <li>
                        <%= link_to 'UnPin', [:unpinned, note], method: :put %>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to 'Pin', [:pinned, note], method: :put %>
                      </li>
                    <% end %>
                  <% else %>
                    <li>
                      <%= link_to 'Restore', [:restore, note], method: :put %>
                    </li>
                    <li>
                      <%= link_to 'Destroy', note_path(note),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %>
                    </li>
                  <% end %>
                </ul>
              </li>
            </div>
          </div>
          <div class='row'>
            <div class='col-sm-9'>
              <%= form.submit 'save' %>
            </div>
            <div class='col-sm-3'>
              <% if note.created_at.strftime('%d-%b-%y') != note.updated_at.strftime('%d-%b-%y') %>
                Edited <%= note.formatted_date %>
              <% end %>
              <br>
              <% if note.created_at.strftime('%H:%M') != note.updated_at. strftime('%H:%M') %>
                Edited <%= note.formatted_time %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/bin.html.erb
<div class='container'>
  <div class='row'>
    <div class='col col-lg-2'>
      <%= content_for (:sidebar) do %>
        <%= render :partial => "layouts/sidebar" %>
      <% end %>
    </div>
    <div class='col col-lg-10'>
      <div class='row'>
        <% if @notes.del.present? %>
          <% @notes.del.each_with_index do |note , index| %>
            <div class='col-sm-3  note_div' data-note-id="<%= note.id %>" id="card-<%= note.id %>">
              <%= render partial: "note" , locals: { note: note} %>
            </div>
            <% if (index + 1) % 4 == 0 %>
              <div class='row'></div>
            <% end %>
          <% end %>
        <% else %>
          <div class="row align-items-center">
              <%= image_tag "binicon.png", height: 100 , width: 10 %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/create.js.erb
$("#notes-container").prepend('<%= j render @note %>');
$('#mynewnote')[0].reset();
location.reload();
$('#mynewnote').modal()
$('#mynewnote').modal('toggle')

app/views/notes/edit.html.erb
<%= render 'edit_modal', note: @note %>

app/views/notes/edit.js.erb
$('.editModal').modal('hide');
$('#mynote').html("<%= j render 'edit_modal', note: @note %>");
$('.editModal').modal('show');

app/views/notes/edit_color.html.erb
<%= form_for @note do |f| %>
  Color: <%= f.select :color , options_for_select(Note::COLOR_TYPE)  %>
  <%= f.submit "Update" %>
<% end %>

app/views/notes/index.html.erb
<div class='container' id="MyNotes">
  <div class='row'>
    <div class='col col-lg-2'>
      <%= content_for (:sidebar) do %>
        <%= render :partial => "layouts/sidebar" %>
      <% end %>
    </div>
    <div class='col col-lg-10'>
      <div class='row'>
        <div class='col col-lg-3'>
        </div>
        <div class='col col-lg-7' id = "cracker1-button">
          <%= link_to new_note_path , remote: true do %>
            <table class="table table-bordered">
              <tr>
                <td>Take a note... </td>
              </tr>
            </table>
          <% end %>
        </div>
      </div>

      <div class='row'>
        <div class='col col-lg-2'>
          <h4>Pinned</h4>
        </div>
      </div>
      <div class='row container'>
        <% (@notes.active & @notes.notdel & @notes.pinned).each_with_index do |note , index| %>
          <div class=" col-sm-3  note_div" data-note-id="<%= note.id %>" id="card-<%= note.id %>">
              <%= render partial: "note" , locals: { note: note} %>
          </div>
          <% if (index + 1) % 4 == 0 %>
            <div class='row'></div>
          <% end %>
        <% end %>
      </div>
      <div class='row'>
        <div class='col col-lg-2'>
          <h4>Others</h4>
        </div>
      </div>
      <div class='row container' id='notes-container'>
        <% (@notes.active & @notes.notdel & @notes.unpinned).each_with_index do |note , index| %>
          <div class="col-sm-3 note_div" data-note-id="<%= note.id %>" id="card-<%= note.id %>" >
            <%= render partial: "note" , locals: { note: note} %>
          </div>
          <% if (index + 1) % 4 == 0 %>
            <div class='row'></div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="pag-bar mt-5 pt-5">
  <%#== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/notes/new.js.erb
$('#mynewnote').html("<%= j render 'new', note: @note %>");
$('#new').modal()
$('#new').modal('toggle')

app/views/notes/show.html.erb
<div style="background-color: <%= @note.color.downcase %>;", class = T >
  <h3>Title</h3>
    <%= @note.title %>
  <h3>Content</h3>
    <%= @note.content %>
  <h3>Label</h3>
  <ul>
    <% @note.labels.each do |label| %>
      <li><%= label.label_name %></li>
    <% end %>
  </ul>
    <% if @note.image.attached? %>
      <%= image_tag (@note.image), height: 100 , width: 200 %>
    <% end %>

  <% if @note.pin == 'no' && @note.stage == 'notdel' && @note.status =='active' %>
    <table>
      <td><h3><%= link_to "Edit", edit_note_path(@note) %> </h3></td>
      <td><%= link_to 'Archived', [:archive, @note], method: :put %></td>
      <td><%= link_to 'Delete', [:soft_delete, @note], method: :put %></td>
      <td><%= link_to 'Pin', [:pin, @note], method: :put %></td>
      <%= link_to "Edit Color", notes_edit_color_path(@note) %>
    </table>
    <%= form_for @note, url: {action: "add_label"} do |form| %>
      <%= form.collection_select(:label_ids, Label.all, :id, :label_name, {}, { multiple: true }) %>
        <br>
        <%= form.submit "Add label" %>
    <% end %>

    <li class="nav-item dropdown px-2" >
      <a class="nav-link dropdown-toggle" href="#" role="button"  data-bs-toggle="dropdown" aria-expanded="false">
        <strong>More..</strong>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Add_label' , notes_path , class: 'navber-brand '%></li>
        <li><%= link_to 'Edit_Note' ,edit_note_path(@note) , class:   'navber-brand' %>
        </li>
        <li><%= link_to 'Delete_Note' , [:soft_delete, @note], method: :put ,   class: 'navber-brand' %></li>
      </ul>
    </li>
  <% end %>

  <% if @note.pin == 'yes' && @note.stage == 'notdel' && @note.status =='active'  %>
      <table>
      <td><h3><%= link_to "Edit", edit_note_path(@note) %> </h3></td>
      <td><%= link_to 'Archived', [:archive, @note], method: :put %></td>
      <td><%= link_to 'Delete', [:soft_delete, @note], method: :put %></td>
      <td><%= link_to 'NotPin', [:notpin, @note], method: :put %></td>
      <%= link_to "Edit Color", edit_note_path(@note) %>
      </table>
      <%= form_for @note, url: {action: "add_label"} do |form| %>
        <%= form.collection_select(:label_ids, Label.all, :id, :label_name, {}, { multiple: true }) %>
        <br>
        <%= form.submit "Add label" %>
      <% end %>
  <% end %>

  <% if @note.stage == 'del' %>
    <table>
    <td><%= link_to 'Restore', [:restore, @note], method: :put %></td>
    <td><%= link_to 'Destroy', note_path(@note),
    method: :delete,
    data: { confirm: 'Are you sure?' } %></td>
    </table>
  <% end %>

  <% if  @note.stage == 'notdel' && @note.status =='archived' %>
    <td><%= link_to 'Delete', [:soft_delete, @note], method: :put %></td>
    <td><h3><%= link_to "Edit", edit_note_path(@note) %> </h3></td>
    <td><%= link_to 'Not_Archived', [:notarchive, @note], method: :put %></td>
    <%= link_to "Edit Color", edit_note_path(@note) %>
    <%= form_for @note, url: {action: "add_label"} do |form| %>
      <%= form.collection_select(:label_ids, Label.all, :id, :label_name, {}, { multiple: true }) %>
      <br>
      <%= form.submit "Add label" %>
    <% end %>
  <% end %>
</div>

app/views/notes/show.js.erb
# $(<%= "card-#{@note.id}" %>).html("<%= j render 'edit_modal', note: @note %>");
# $('#editModal').modal('show');

app/views/notes/show_label.html.erb
<% @notes.each do |note| %>
  <div style="background-color: <%= note.color.downcase %>", class='index' >
    <h2>Title</h2>
    <%= note.title %>
    <h3><%= link_to "Show", note %> </h3>
  </div>
<% end %>

app/views/notes/update.js.erb
$("#card-<%= @note.id %>").html("<%= j render partial: 'note', locals: { note: @note } %>");
$('.editModal').modal()
$('.editModal').modal('toggle')