config/routes.rb
Rails.application.routes.draw do

  root 'notes#index'

  # root 'pages#home'


  devise_for :users, controllers: {
    registrations:  'users/registrations',
    sessions:  'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'notes/archived', :to => 'notes#archived'
  get 'notes/bin', :to => 'notes#bin'
  get 'notes/show_label', :to => 'notes#show_label'
  get 'notes/edit_color', :to => 'notes#edit_color'
  get "note/notesshow" => 'note#notesshow', :as => :notesshow
  get 'notes/search', :to => 'notes#search'
  get '/update/:id' , to: "root#update"
  get 'notes/label_note', :to => 'notes#label_note'
  # get 'notes/home', :to => 'notes#home'
  # get 'notes/user', :to => 'notes#user'

  resources :notes do
    member do
      put :archive
      put :active
      put :notarchive
      put :deleted_at
      patch :soft_delete
      put :restore
      put :pinned
      put :unpinned
      patch :add_label
      get :update_color
      post :create_copy
      post :copy
      post :copy_note
      delete :delete_image
      delete :delete_background_image
      patch :set_reminder
      post :send_mail
    end
  end
  resources :labels

  # Rails.application.routes.draw do
  get 'pages/home'
  # resources :consumers
  # # mount_devise_token_auth_for 'User', at: 'auth'

  #   root to: 'users#new'

  #   get 'users/new' => 'users#new', as: :new_user
  #   post 'users' => 'users#create'

  #   # ----- add these lines here: -----

  #   # log in page with form:
  #   get '/login'     => 'sessions#new'

  #   # create (post) action for when log in form is submitted:
  #   post '/login'    => 'sessions#create'

  #   # delete action to log out:
  #   delete '/logout' => 'sessions#destroy'

  #     # ----- end of added lines -----

  # end

end

app/models/label.rb
class Label < ApplicationRecord
  has_and_belongs_to_many :notes

   validates :label_name, uniqueness: true , presence: true

   def name_with_initial
      "#{label_name}"
    end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :authenticate_user!

    def index
      @labels = Label.all
      @labels = Label.where("label_name LIKE ? ","%#{params[:query.downcase]}%" )
    end

    def show
      @notes = Note.all
      @labels = Label.all
      @label = Label.find(params[:id])
      @notes = @label.notes
    end

    def shownotes
      @label = Label.find(params[:id])
      @notes = @label.notes
    end

    def new
      @label = Label.new

    end

    def create
      @label = Label.new(label_params)
      if @label.save
         redirect_to @label
      else
        render :new
      end
    end

    def edit
      @label = Label.find(params[:id])
    end

    def update
      @label = Label.find_by_id(params[:id])

      if @label.update(label_params)
        redirect_to label_path(@label)
      else
        render :edit
      end
    end

    def destroy
      @label = Label.find(params[:id])
      @label.destroy
      redirect_to root_path :id
    end

    def new_label
      @labels = Label.all
    end


   private
      def set_label
        @label = Label.find(params[:id])
      end

      def label_params
        params.require(:label).permit(:label_name , :note_id)
      end
  end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_new.html.erb
<div id="new" class="modal fade" role="model-dialog">
  <div class="modal-dialog modal-lg" >
    <div class="modal-content">
      <%= form_for(label, remote: true) do |form| %>
        <div style="background-color: <%= @label.color.downcase %>;", class = T >
          <div class = "row">
            <div class = "col">
              <%= form.text_field :label_name, placeholder: "Title" %>
            </div>
            <% label.errors.full_messages_for(:label_name).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
            <%= form.submit "save" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/labels/_new_label.html.erb
<div id="new_label" class="modal fade" role="model-dialog">
  <div class="modal-dialog modal-lg" >
    <div class="modal-content">
      <%= form_for @label , url: {action: "create" } do |form| %>
        <div class='new'>
          <%= form.text_field :label_name, placeholder: 'Create new label' %>
          <% label.errors.full_messages_for(:label_name).each do |message| %>
            <div><%= message %></div>
          <% end %>
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/labels/edit.html.erb
<h1>Edit Label</h1>
  <%= form_for @label do |f| %>
  Label_name: <%= f.text_field :label_name %>
  <%= f.submit "Update" %>
<% end %>

app/views/labels/index.html.erb
<h2> Label </h2>
<% @labels.each  do |label| %>
  <table>
  <tr>
    <td><%= label.label_name %></td>
    <td><h3><%= link_to "Edit", edit_label_path(label) %> </h3></td>
    <td><%= link_to 'Destroy', label,
    method: :delete,
    data: { confirm: 'Are you sure?' } %></td>
  </tr>
</table>
<% end %>

app/views/labels/new.html.erb
<%= render "form", label: @label %>
<tr>
 <td><%= link_to "Show label", labels_path %></td>
</tr>

app/views/labels/new.js.erb
$('#mylabel').html("<%= j render 'new_label', label: @label %>");
$('#new_label').modal('show');

app/views/labels/show.html.erb
<div class="container">
  <div class="row">
    <div class="col col-lg-2">
      <%= content_for (:sidebar) do %>
        <%= render :partial => "layouts/sidebar" %>
      <% end %>
    </div>
    <div class="col col-lg-10">
      <div class= "row"  class="rounded-0">
        <% @notes.each do |note| %>
          <div class="col-sm-3 mb-3 mb-sm-2">
            <div class="card" style="background-color: <%= note.color.downcase %>;">
              <div class="card-body" >
                <%= link_to note_path(note) , remote: true do %>
                  <div class = "row" >
                    <div class = "col" >
                      <strong><%= note.title %></strong>
                    </div>
                  </div>
                  <div class = "row" >
                    <div class = "col">
                      <%= note.content %>
                    </div>
                  </div>
                  <div class = "row" >
                    <div class = "col">
                      <ul>
                        <% note.labels.each do |label| %>
                          <li><%= label.label_name %></li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                  <div class = "row" >
                    <div class = "col" >
                      <%= link_to "Show", note %>
                    </div>
                  </div>
                  <div class = "row" >
                    <div class = "col" >
                    <%= link_to 'Not_Archived', [:notarchive, note], method: :put %>
                    </div>
                  </div>
                <% end %>
              </div>
              <ul class="nav-item dropdown px-2" >
                <a class="nav-link dropdown-toggle" href="#" role="button"    data-bs-toggle="dropdown" aria-expanded="false">
                    <strong>more..</strong>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to 'Create Copy', copy_note_path(note), method: :post%>
                  </li>
                  <li>
                    <%= link_to 'Delete Note', [:soft_delete, note], method: :put %>
                  </li>
                </ul>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id='mynote'></div>