config/routes.rb
Rails.application.routes.draw do

  root 'notes#index'

  # root 'pages#home'


  devise_for :users, controllers: {
    registrations:  'users/registrations',
    sessions:  'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'notes/archived', :to => 'notes#archived'
  get 'notes/bin', :to => 'notes#bin'
  get 'notes/show_label', :to => 'notes#show_label'
  get 'notes/edit_color', :to => 'notes#edit_color'
  get "note/notesshow" => 'note#notesshow', :as => :notesshow
  get 'notes/search', :to => 'notes#search'
  get '/update/:id' , to: "root#update"
  get 'notes/label_note', :to => 'notes#label_note'
  # get 'notes/home', :to => 'notes#home'
  # get 'notes/user', :to => 'notes#user'

  resources :notes do
    member do
      put :archive
      put :active
      put :notarchive
      put :deleted_at
      patch :soft_delete
      put :restore
      put :pinned
      put :unpinned
      patch :add_label
      get :update_color
      post :create_copy
      post :copy
      post :copy_note
      delete :delete_image
      delete :delete_background_image
      patch :set_reminder
      post :send_mail
    end
  end
  resources :labels

  # Rails.application.routes.draw do
  get 'pages/home'
  # resources :consumers
  # # mount_devise_token_auth_for 'User', at: 'auth'

  #   root to: 'users#new'

  #   get 'users/new' => 'users#new', as: :new_user
  #   post 'users' => 'users#create'

  #   # ----- add these lines here: -----

  #   # log in page with form:
  #   get '/login'     => 'sessions#new'

  #   # create (post) action for when log in form is submitted:
  #   post '/login'    => 'sessions#create'

  #   # delete action to log out:
  #   delete '/logout' => 'sessions#destroy'

  #     # ----- end of added lines -----

  # end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col col-lg-2   sidebar">
  <div class = "row" >
  <div class="col col-lg-3">
    <%= image_tag "notesicon.jpg", height: 50 %>
  </div>
  <div class="col col-lg-9">
  <%= link_to "Notes", notes_path %>
  </div>
  </div>
  <div class = "row" >
    <div class="col col-lg-3">
      <%= image_tag "addnotesicon.png", height: 20 %>
    </div>
    <div class="col col-lg-9">
      <%= link_to new_note_path , remote: true do %>
        <h7>Add Notes</h7>
      <% end %>
    </div>
  </div>
  <div class = "row" >
    <div class="col col-lg-3">
      <%= image_tag "archive.jpg", height: 20 %>
    </div>
    <div class="col col-lg-9">
      <%= link_to "Archive Notes", notes_archived_path %>
    </div>
  </div>
  <div class = "row" >
    <div class="col col-lg-3">
      <%= image_tag "binicon.png", height: 20 %>
    </div>
    <div class="col col-lg-9">
      <%= link_to "Show Bin " , notes_bin_path %>
    </div>
  </div>
  <div class = "row" >
    <div class="col col-lg-3">
      <%= image_tag "editlabelicon.png", height: 20 %>
    </div>
    <div class="col col-lg-9">
      <%#= link_to "Create Label", new_label_path %>
      <%= link_to 'edit_label', new_label_path, :remote => true %>
    </div>
  </div>
  <% @labels.each do |label| %>
    <div class="row">
      <div class="col col-lg-3">
        <%= image_tag "labelicon.png", height: 30 %>
      </div>
      <div class="col col-lg-9">
        <%#= link_to label.label_name , notes_label_note_path(label) %>
        <%= link_to label.label_name , label_path(label) %>
      </div>
    </div>
  <% end %>
</div>
<div id='mylabel'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keepnotes</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= favicon_link_tag asset_path('notesicon.jpg') %>
  <body>
    <ul>
      <% if user_signed_in? %>
        <li><%= link_to "Hi, #{current_user.email}", edit_user_registration_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>
   <%= render '/shared/header' %>
   <%= yield :sidebar %>
    <%= yield %>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">

     <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%#= javascript_include_tag 'notes' %>
     </script>
     <div id='mynote'></div>
     <div id='mynewnote'></div>
     <div id='mylabel'></div>
     <p class="navbar-text float-right">
  </body>
</html>